name: Notificar Deploid

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    environment: DEVELOP
    
    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Modificar algo (dummy)
        run: |
          echo "Deploy: $(date)" >> deploy.log

      - name: Commit cambios
        run: |
          git add deploy.log
          git commit -m "Enviado a deploy" || echo "No hay cambios para commitear"

      - name: Push cambios
        run: |
          git push origin develop
