name: Notificar Deploid

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    environment: DEVELOP
    permissions:
      contents: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Crear tag
        run: |
          # Obtener la fecha y hora actual
          DATETIME=$(date +"%Y%m%d-%H%M%S")
          # Obtener la rama de origen (por defecto main)
          BRANCH=${GITHUB_REF_NAME:-main}
          # Obtener el nombre del usuario que inició la action
          USER=${GITHUB_ACTOR:-unknown}
          # Crear el nombre del tag
          TAG_NAME="dev-${DATETIME}-${BRANCH}-${USER}"
          # Crear el tag
          git tag $TAG_NAME
          echo "Tag creado: $TAG_NAME"

      - name: Push tag
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} --tags 